version: "3"
services:
  db:
    image: "postgres:alpine"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres

  paste:
    image: "dessolo/paste:latest"
    build: .
    ports:
      - 8000:8000
    environment:
      - DEBUG=True
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
    command: runserver 0.0.0.0:8000
